import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface":                  "#0c1322",
        "surface-dim":              "#0c1322",
        "surface-bright":           "#323949",
        "surface-container-lowest": "#070e1d",
        "surface-container-low":    "#141b2b",
        "surface-container":        "#191f2f",
        "surface-container-high":   "#232a3a",
        "surface-container-highest":"#2e3545",
        "surface-variant":          "#2e3545",
        "surface-tint":             "#adc6ff",
        "on-surface":               "#dce2f7",
        "on-surface-variant":       "#c2c6d6",
        "inverse-surface":          "#dce2f7",
        "inverse-on-surface":       "#293040",
        "outline":                  "#8c909f",
        "outline-variant":          "#424754",
        "background":               "#0c1322",
        "on-background":            "#dce2f7",
        "primary":                  "#adc6ff",
        "on-primary":               "#002e6a",
        "primary-container":        "#4d8eff",
        "on-primary-container":     "#00285d",
        "primary-fixed":            "#d8e2ff",
        "primary-fixed-dim":        "#adc6ff",
        "on-primary-fixed":         "#001a42",
        "on-primary-fixed-variant": "#004395",
        "inverse-primary":          "#005ac2",
        "secondary":                "#4cd7f6",
        "on-secondary":             "#003640",
        "secondary-container":      "#03b5d3",
        "on-secondary-container":   "#00424e",
        "secondary-fixed":          "#acedff",
        "secondary-fixed-dim":      "#4cd7f6",
        "on-secondary-fixed":       "#001f26",
        "on-secondary-fixed-variant":"#004e5c",
        "tertiary":                 "#ffb786",
        "on-tertiary":              "#502400",
        "tertiary-container":       "#df7412",
        "on-tertiary-container":    "#461f00",
        "tertiary-fixed":           "#ffdcc6",
        "tertiary-fixed-dim":       "#ffb786",
        "on-tertiary-fixed":        "#311400",
        "on-tertiary-fixed-variant":"#723600",
        "error":                    "#ffb4ab",
        "on-error":                 "#690005",
        "error-container":          "#93000a",
        "on-error-container":       "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm:      "0.125rem",
        md:      "0.25rem",
        lg:      "0.375rem",
        xl:      "0.5rem",
        full:    "9999px",
      },
      spacing: {
        "unit":             "4px",
        "gutter":           "16px",
        "margin-mobile":    "16px",
        "margin-desktop":   "24px",
        "container-max":    "1600px",
      },
      fontFamily: {
        sans:         ["Inter", "sans-serif"],
        mono:         ["JetBrains Mono", "monospace"],
        "body-base":  ["Inter", "sans-serif"],
        "body-sm":    ["Inter", "sans-serif"],
        "headline-sm":["Inter", "sans-serif"],
        "headline-md":["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "code-base":  ["JetBrains Mono", "monospace"],
        "code-sm":    ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg":  ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-base":   ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm":     ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "code-base":   ["13px", { lineHeight: "20px" }],
        "code-sm":     ["11px", { lineHeight: "16px" }],
        "label-caps":  ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
      },
      animation: {
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
    },
  },
  plugins: [],
};

export default config;
